import { Quicksand,Roboto } from "next/font/google";
import "../globals.css";

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
  weight: ['400', '700'], // optional: specify weights you want to use
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ['400', '700'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${quicksand.variable} ${roboto.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
